// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-nMaW6uwtkQcodfvZgJzKVi-QXZFZGdI',
    appId: '1:278467773883:web:6873fee44cc14c5457f09e',
    messagingSenderId: '278467773883',
    projectId: 'studyflow-62c53',
    authDomain: 'studyflow-62c53.firebaseapp.com',
    storageBucket: 'studyflow-62c53.firebasestorage.app',
    measurementId: 'G-3RGY83M3C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_sqWrR_FNi1a-coDNDBi5P_VwJdDjR_4',
    appId: '1:278467773883:android:377fe2a76f1d030557f09e',
    messagingSenderId: '278467773883',
    projectId: 'studyflow-62c53',
    storageBucket: 'studyflow-62c53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcgU6BgrlXWU9IjNiYwMqL3Z5k-wc-GgI',
    appId: '1:278467773883:ios:d67bedc8a26da85f57f09e',
    messagingSenderId: '278467773883',
    projectId: 'studyflow-62c53',
    storageBucket: 'studyflow-62c53.firebasestorage.app',
    iosBundleId: 'com.example.appMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcgU6BgrlXWU9IjNiYwMqL3Z5k-wc-GgI',
    appId: '1:278467773883:ios:d67bedc8a26da85f57f09e',
    messagingSenderId: '278467773883',
    projectId: 'studyflow-62c53',
    storageBucket: 'studyflow-62c53.firebasestorage.app',
    iosBundleId: 'com.example.appMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-nMaW6uwtkQcodfvZgJzKVi-QXZFZGdI',
    appId: '1:278467773883:web:5139e30f6dc715c557f09e',
    messagingSenderId: '278467773883',
    projectId: 'studyflow-62c53',
    authDomain: 'studyflow-62c53.firebaseapp.com',
    storageBucket: 'studyflow-62c53.firebasestorage.app',
    measurementId: 'G-DSHGPT0CKV',
  );
}
